name: Machine Learning Pipeline execution

on: [workflow_dispatch]
env:
  APPLICATION_NAME: startupapp
jobs:
  Alint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up Python & Python Location
        run: |
          echo "pythonLocation=/opt/hostedtoolcache/Python/3.12.4/x64" >> $GITHUB_ENV
          echo "Python is located at $pythonLocation"

      - name: Setup Python environment
        uses: actions/setup-python@v2

      - name: Upgrade PIP and Install requirements
        run: |
          pip install --upgrade pip
          pip install --quiet --requirement requirements.txt

      - name: Lint code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 *.py

      - name: Run unit tests
        run: |
          python -m unittest --verbose --failfast      

  Bupdate_counter:
    needs: [Alint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository using PAT
        uses: actions/checkout@v2
        with:
          repository: NubeEra-Temps/MLPipeline-Actions
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update counter
        run: |
          python ./Counters/update_counter.py
        shell: bash
        continue-on-error: false
        env:
          GITHUB_OUTPUT: ${{ steps.update_counter.outputs.counter }}

      - name: Determine counter value
        id: determine_counter
        run: |
          if [ -z "${{ steps.update_counter.outputs.counter }}" ]; then
            echo "counter=1" >> $GITHUB_ENV
          else
            echo "counter=${{ steps.update_counter.outputs.counter }}" >> $GITHUB_ENV
          fi

      - name: Get counter value
        run: |
          echo $GITHUB_ENV
          echo "Counter value is ${{ env.counter }}"          
    
      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email '${{ secrets.GIT_EMAIL }}'  
          git add .
          git commit -m 'Update counter'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Get counter value
        id: get_counter
        run: echo "Counter value is ${{ steps.update_counter.outputs.counter }}"

  Cbuild_image:
    needs: [Bupdate_counter]
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
    
    - name: Get counter value
      run: echo "Counter value is ${{ env.counter }}"
    ################### DISABLE SSH ##########################
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     file: docker/Dockerfile # Path to your Dockerfile
    #     push: true
    #     tags: docker.io/${{ secrets.DOCKER_USERNAME }}/deploy-ml-model:${{ env.counter }}


    # - uses: mr-smithers-excellent/docker-build-push@v6
    #   name: Build & push Docker image
    #   with:
    #     image: docker.io/${{ secrets.DOCKER_USERNAME }}/deploy-ml-model
    #     tags: v1, latest
    #     registry: docker.io
    #     context: .
    #     dockerfile: docker/Dockerfile
    #     # multiPlatform: true
    #     # platform: linux/amd64,linux/arm64,linux/arm/v7
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}