name: Machine Learning Pipeline execution

on: [workflow_dispatch]
env:
  APPLICATION_NAME: startupapp
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        run: echo "pythonLocation=/opt/hostedtoolcache/Python/3.12.4/x64" >> $GITHUB_ENV

      - name: Use Python Location
        run: echo "Python is located at $pythonLocation"

      - name: Setup Python environment
        uses: actions/setup-python@v2

      # - name: Upgrade pip version
      #   run: pip install --upgrade pip

      # - name: Install requirements
      #   run: pip install --quiet --requirement requirements.txt

      # - name: Lint code
      #   run: |
      #     flake8 --ignore=E501,E231 *.py
      #     pylint --disable=C0301 *.py

      # - name: Run unit tests
      #   run: |
      #     python -m unittest --verbose --failfast

      # - name: Find Value for secrets.ML_SERVICE_ACCT_KEY variable
      #   run:  |
      #     echo "________________________________________________"
      #     echo "Value is    ${{ secrets.ML_SERVICE_ACCT_KEY }}"
      #     echo "________________________________________________"

  build_image:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - name: List files for debugging
      run: |
        ls -R
        pwd
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    # - uses: mr-smithers-excellent/docker-build-push@v6
    #   name: Build & push Docker image
    #   with:
    #     image: mujahed/deploy-ml-model
    #     tags: v1, latest
    #     registry: docker.io
    #     dockerfile: docker/Dockerfile
    #     # multiPlatform: true
    #     # platform: linux/amd64,linux/arm64,linux/arm/v7
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}